server.port=8080

# Server URL
shareit-server.url=http://localhost:9090

# Logging
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.ru.practicum.shareit.client=DEBUG
logging.level.ru.practicum.shareit.gateway=DEBUG

# ????????? ???????????????? JPA ? DataSource
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration